(() => {
  var __create = Object.create;
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __getProtoOf = Object.getPrototypeOf;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
    get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
  }) : x)(function(x) {
    if (typeof require !== "undefined") return require.apply(this, arguments);
    throw Error('Dynamic require of "' + x + '" is not supported');
  });
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
    // If the importer is in node compatibility mode or this is not an ESM
    // file that has been converted to a CommonJS file using a Babel-
    // compatible transform (i.e. "__esModule" has not been set), then set
    // "default" to the CommonJS "module.exports" for node compatibility.
    isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
    mod
  ));

  // <stdin>
  console.log("This site was generated by Hugo.");
  document.addEventListener("DOMContentLoaded", () => {
    const navToggleBtn = document.querySelector("[data-nav-toggle]");
    const navEl = document.querySelector("[data-nav]");
    if (navToggleBtn && navEl) {
      navToggleBtn.addEventListener("click", () => {
        const open = navEl.classList.toggle("is-open");
        navToggleBtn.setAttribute("aria-expanded", open ? "true" : "false");
      });
    }
    const toc = document.querySelector(".toc-dropdown");
    if (toc) {
      toc.addEventListener("click", (e) => {
        const target = e.target;
        if (target && target.tagName === "A") {
          toc.open = false;
        }
      });
    }
    const searchInput = document.getElementById("archive-search");
    const groupsEl = document.getElementById("archive-groups");
    const resultsEl = document.getElementById("archive-results");
    if (searchInput && groupsEl && resultsEl) {
      let fuseInstance = null;
      let indexData = null;
      const renderResults = (items) => {
        if (!Array.isArray(items)) return;
        if (items.length === 0) {
          resultsEl.innerHTML = "<p>No results</p>";
          return;
        }
        const html = items.map((r) => {
          const item = r.item || r;
          const title = item.title || "";
          const date = item.date || "";
          const link = item.permalink || "#";
          const summary = item.summary || "";
          return `
          <article class="archive-result">
            <h3><a href="${link}">${title}</a></h3>
            <time class="date">${date}</time>
            <p class="summary">${summary}</p>
          </article>
        `;
        }).join("");
        resultsEl.innerHTML = html;
      };
      const showGroups = () => {
        groupsEl.hidden = false;
        resultsEl.hidden = true;
      };
      const showResults = () => {
        groupsEl.hidden = true;
        resultsEl.hidden = false;
      };
      const initFuse = async () => {
        if (fuseInstance) return fuseInstance;
        if (!indexData) {
          try {
            const res = await fetch("/index.json", { cache: "no-store" });
            if (!res.ok) return null;
            indexData = await res.json();
          } catch (e) {
            return null;
          }
        }
        if (!Array.isArray(indexData)) return null;
        const options = {
          includeScore: true,
          ignoreLocation: true,
          minMatchCharLength: 2,
          threshold: 0.3,
          keys: [
            { name: "title", weight: 2 },
            { name: "summary", weight: 1 },
            { name: "tags", weight: 0.5 },
            { name: "categories", weight: 0.5 },
            { name: "content", weight: 0.25 }
          ]
        };
        if (window.Fuse) {
          fuseInstance = new window.Fuse(indexData, options);
        }
        return fuseInstance;
      };
      searchInput.addEventListener("input", async (ev) => {
        const q = (ev.target.value || "").trim();
        if (q.length === 0) {
          showGroups();
          return;
        }
        const fuse = await initFuse();
        if (!fuse) return;
        const results = fuse.search(q).slice(0, 50);
        renderResults(results);
        showResults();
      });
    }
    (async () => {
      const article = document.querySelector("article.content");
      if (!article) return;
      try {
        const getImageDimensions = (src, imgEl) => new Promise((resolve) => {
          const w = imgEl && imgEl.naturalWidth || 0;
          const h = imgEl && imgEl.naturalHeight || 0;
          if (w > 0 && h > 0) {
            resolve({ width: w, height: h });
            return;
          }
          const probe = new Image();
          probe.onload = () => {
            resolve({
              width: probe.naturalWidth || 1600,
              height: probe.naturalHeight || 900
            });
          };
          probe.onerror = () => resolve({ width: 1600, height: 900 });
          probe.src = src;
        });
        const { default: PhotoSwipeLightbox } = await import("https://cdn.jsdelivr.net/npm/photoswipe@5/dist/photoswipe-lightbox.esm.min.js");
        const lightbox = new PhotoSwipeLightbox({
          gallery: "article.content",
          children: "a[data-pswp-width]",
          wheelToZoom: true,
          // dynamic import of core
          pswpModule: () => import("https://cdn.jsdelivr.net/npm/photoswipe@5/dist/photoswipe.esm.min.js")
        });
        lightbox.init();
        const anchorItems = Array.from(article.querySelectorAll("a[href]:not([data-pswp-width])")).map((a) => ({ a, img: a.querySelector("img") })).filter((x) => x.img);
        if (anchorItems.length) {
          const { default: LB } = await import("https://cdn.jsdelivr.net/npm/photoswipe@5/dist/photoswipe-lightbox.esm.min.js");
          const lbLinks = new LB({
            wheelToZoom: true,
            pswpModule: () => import("https://cdn.jsdelivr.net/npm/photoswipe@5/dist/photoswipe.esm.min.js")
          });
          lbLinks.init();
          anchorItems.forEach(({ a, img }) => {
            a.style.cursor = "zoom-in";
            a.addEventListener("click", async (e) => {
              e.preventDefault();
              const src = a.getAttribute("href");
              const dims = await getImageDimensions(src, img);
              lbLinks.loadAndOpen(0, [{ src, width: dims.width, height: dims.height, alt: img.alt || "" }]);
            });
          });
        }
        const orphanImgs = Array.from(article.querySelectorAll("img:not(a img)"));
        if (orphanImgs.length) {
          const { default: LB } = await import("https://cdn.jsdelivr.net/npm/photoswipe@5/dist/photoswipe-lightbox.esm.min.js");
          const lb = new LB({
            wheelToZoom: true,
            pswpModule: () => import("https://cdn.jsdelivr.net/npm/photoswipe@5/dist/photoswipe.esm.min.js")
          });
          lb.init();
          orphanImgs.forEach((img) => {
            img.style.cursor = "zoom-in";
            img.addEventListener("click", async () => {
              const src = img.currentSrc || img.src;
              const dims = await getImageDimensions(src, img);
              lb.loadAndOpen(0, [{ src, width: dims.width, height: dims.height, alt: img.alt || "" }]);
            });
          });
        }
      } catch (e) {
      }
    })();
    document.addEventListener("click", async (ev) => {
      const btn = ev.target.closest("[data-copy-code]");
      if (!btn) return;
      const wrapper = btn.closest(".codeblock");
      if (!wrapper) return;
      const pre = wrapper.querySelector(".highlight pre");
      if (!pre) return;
      try {
        const text = pre.textContent || "";
        await navigator.clipboard.writeText(text);
        const original = btn.textContent;
        btn.textContent = "Copied";
        setTimeout(() => {
          btn.textContent = original;
        }, 1200);
      } catch (e) {
      }
    });
    const themeBtn = document.querySelector("[data-theme-toggle]");
    if (themeBtn) {
      const root = document.documentElement;
      const applyTheme = (theme) => {
        root.setAttribute("data-theme", theme);
        localStorage.setItem("theme", theme);
        themeBtn.setAttribute("aria-label", theme === "dark" ? "Switch to light theme" : "Switch to dark theme");
      };
      const current = root.getAttribute("data-theme") || (window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
      applyTheme(current);
      themeBtn.addEventListener("click", () => {
        const next = root.getAttribute("data-theme") === "dark" ? "light" : "dark";
        applyTheme(next);
        try {
          window.dispatchEvent(new Event("themechange"));
        } catch (_) {
        }
      });
    }
  });
})();
